### ISSUE TITLE
Uncaught TypeError: this._each is not a function

### ISSUE THREAD

**Issue by pjw345** [newrelic/newrelic-browser-agent#1201]
We see console errors constantly as in they are appearing every second in the console.  Whilst it does not appear to affect the functionality of the browser it is slowing it down.

legacy-build.min.js:1 Uncaught TypeError: this._each is not a function
    at e (legacy-build.min.js:1:14513)
    at nr-spa-1.267.0.min.js:2:81604
    at Array.forEach (<anonymous>)
    at y.ce [as onFinished] (nr-spa-1.267.0.min.js:2:81583)
    at y.finish (nr-spa-1.267.0.min.js:2:76545)
    at nr-spa-1.267.0.min.js:2:76118

Our provider has installed the apm and infrastructure agents, so we have no control over how or what they have installed, but have asked me to reach out to you!

**Comment by cwli24** [comment]
I took a look at a sample site using this exact script (from Magento2). Here are the findings:

> Object.values – which we reasonably use because it’s inherent javascript – is returning empty for an empty array, which is the expected behavior. However, on the sample live site, it’s returning an array of 35 (prototype) functions… Which are each getting called by us when we use Object.values with any array.

Native code behavior:
![image](https://github.com/user-attachments/assets/3898d027-1820-4306-9a84-0bcae037f144)

Mutated code behavior:
![image](https://github.com/user-attachments/assets/adc4e02d-2dca-4cd9-8bba-d3ed5e0263c9)

As we strongly believe the fundamental behavior of Object.values([]) should be reliably native, the fault & burden of such a change should fall on the library causing it.
In this case, it seems to be this legacy-build script from Magento2 that’s overwriting this native function and altering its behavior.

Source fn of the redefined `Object.values`:
<img width="831" alt="image" src="https://github.com/user-attachments/assets/03b08787-b5e0-4dc6-895a-70478ecd93bb">

**Comment by kiatng** [comment]
This affects OpenMage as well.
