### ISSUE TITLE
Fetch with empty url causes distributed tracing error

### ISSUE THREAD

**Issue by gndk** [newrelic/newrelic-browser-agent#618]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The New Relic script inserted by the PHP agent throws an error in a portion of the code related to distributed tracing if `fetch()` is called with an empty string as the url. This meant that the form could not be submitted. In our case the intended purpose was to submit form data to the current url, so I replaced the empty string with `window.location.href`.

## Steps to Reproduce

Code snippet that causes the error:

```js
let response;

try {
  response = await fetch(
    '',
    {
      method: 'POST',
      body: new FormData(form),
      redirect: 'follow',
    },
  );
} catch (error) {
  Sentry.captureException(error);
  return;
}
if (response.status !== 200) {
  Sentry.captureMessage('Response code should have been 200 Ok');
}

window.location.href = response.url;
```

The fix is

```diff
response = await fetch(
-  '',
+  window.location.href,
  {
    method: 'POST',
    body: new FormData(form),
    redirect: 'follow',
  },
);
```

## Expected Behavior

The New Relic tracking script should never cause the main functionality of the site to stop working.

Implement better error handling or use same behavior as `fetch()` (`window.location.href` if url is empty string).

## Relevant Logs / Console output

```
TypeError: Cannot read properties of undefined (reading 'sameOrigin')
  at W.isAllowedOrigin(/something:5:39342)
  at W.shouldGenerateTrace(/something:5:39176)
  at W.generateTracePayload(/something:5:38076)
  at d.w(/something:5:42804)
  at Object.v [as emit](/something:5:7700)
  at Object.v [as emit](/something:5:7638)
  at e.<computed>(/something:5:16316)
  at fetch(./node_modules/@sentry/utils/esm/instrument.js:142:28)
  at call(./somescript.js:263:22)
  at tryCatch(./somescript.js:2:1)
  at _invoke(./somescript.js:2:1)
  at key(./somescript.js:2:1)
  at asyncGeneratorStep(./somescript.js:2:1)
  at _next(./somescript.js:2:1)
  at <anonymous>(./somescript.js:2:1)
  at nrWrapper(/something:5:14381)
  at new Promise(<anonymous>)
  at new Promise(/something:5:18786)
  at apply(./somescript.js:2:1)
  at apply(./somescript.js:248:19)
  at sentryWrapped(./node_modules/@sentry/browser/esm/helpers.js:90:17)
  at HTMLFormElement.nrWrapper(/something:5:14381)
```
## Your Environment

Latest Chrome on Mac

New Relic PHP Agent v10.11.0.3 with browser auto instrumentation enabled.

No idea what the browser agent version is, but I guess latest as of today. The inserted code mentions `nr-loader-spa-1.236.0.min.js.LICENSE.txt`.

**Comment by patrickhousley** [comment]
Hi @gndk This issue should be resolved with release [1.238.0](https://github.com/newrelic/newrelic-browser-agent/releases/tag/v1.238.0). Can you please update and verify your issue is resolved?

**Comment by patrickhousley** [comment]
Hi @gndk. I am closing this issue as it has been resolved in 1.238.0. Please let us know if you are still experiencing this issue after upgrading.
