### ISSUE TITLE
Remove label github action stopped working

### ISSUE THREAD

**Issue by martinkuba** [newrelic/newrelic-browser-agent#88]
## Description
The Remove Label github action is now failing with the error below. This is new behavior.

```
Run andymckay/labeler@master
TypeError: Cannot read property 'pull_request' of undefined
    at getIssueNumber (/home/runner/work/_actions/andymckay/labeler/master/label.js:32:59)
    at label (/home/runner/work/_actions/andymckay/labeler/master/label.js:50:21)
    at Object.<anonymous> (/home/runner/work/_actions/andymckay/labeler/master/label.js:99:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

## Steps to Reproduce

Add the `safe to test` label to a PR. Push a new commit to the PR, which will trigger this workflow. Note that the `safe to test` label has not been removed.

## Expected Behavior

The `safe to test` label should be removed when a new commit is pushed to a PR.

**Comment by metal-messiah** [comment]
#### There is a broken source on our dependency included with this action.

(Issue reported on AndyMcKay repo)[https://github.com/andymckay/labeler/issues/28]
(PR to fix the issue on AndyMcKay repo)[https://github.com/andymckay/labeler/pull/27]

##### Possible courses of Action:
- Wait for PR to be merged into AndyMcKay repo (unknown amount of time)
- Use new dependency / fork and change his / make our own Label tool.

**Comment by metal-messiah** [comment]
At this point in time, it seems clear the dependent lib will not be updated.  We should re-evaluate what we want to do here.
